export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_LOGIN_STARTED = 'USER_LOGIN_STARTED'
export const USER_LOGIN_SUCCEEDED = 'USER_LOGIN_SUCCEEDED'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

export const USER_REGISTER_STARTED = 'USER_REGISTER_STARTED'
export const USER_REGISTER_SUCCEEDED = 'USER_REGISTER_SUCCEEDED'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'
