export const ADD_CARRIER_STARTED = 'ADD_CARRIER_STARTED'
export const ADD_CARRIER_SUCCEEDED = 'ADD_CARRIER_SUCCEEDED'
export const ADD_CARRIER_FAILED = 'ADD_CARRIER_FAILED'

export const UPDATE_CARRIER_STARTED = 'UPDATE_CARRIER_STARTED'
export const UPDATE_CARRIER_SUCCEEDED = 'UPDATE_CARRIER_SUCCEEDED'
export const UPDATE_CARRIER_FAILED = 'UPDATE_CARRIER_FAILED'

export const GET_CARRIER_LIST_STARTED = 'GET_CARRIER_LIST_STARTED'
export const GET_CARRIER_LIST_SUCCEEDED = 'GET_CARRIER_LIST_SUCCEEDED'
export const GET_CARRIER_LIST_FAILED = 'GET_CARRIER_LIST_FAILED'
